# Generated by Django 6.0.5 on 2026-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to='media/testimonials/'),
        ),
    ]
