# Generated by Django 6.0.5 on 2026-07-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blogpost_feature_image_alter_testimonial_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='feature_image',
            new_name='featured_image',
        ),
    ]
